networks:
  tcalendar:
    ipam:
      config:
        - subnet: 172.32.32.0/24

services:
  tcalendar-frontend:
    image: linagora/twake-calendar-web:branch-master
    container_name: twake_calendar_frontend
    networks:
      - tcalendar
    ports:
      - "3000:80"
    volumes:
      - ./frontend/env.js:/usr/share/nginx/html/.env.js
    depends_on:
      - tcalendar-side-service
      - web-proxy

  tcalendar-side-service:
    image: linagora/twake-calendar-side-service:branch-master
    container_name: tcalendar-side-service.linagora.local
    depends_on:
      - ferretdb
      - rabbitmq
      - sabre_dav
      - redis
    networks:
      - tcalendar
    extra_hosts:
      - "sabre-dav.linagora.local:172.32.32.32"
    volumes:
      - ./conf-side-service:/root/conf
    ports:
      - "8088:80"
      - "8000:8000"

  fe-calendar:
    image: linagora/esn-frontend-calendar:govmu-02
    hostname: calendar.linagora.local
    environment:
      - OPENPAAS_URL=http://tcalendar-side-service.linagora.local
    volumes:
      - ./frontend/calendar/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - tcalendar

  fe-excal:
    image: linagora/esn-frontend-calendar-public:main
    hostname: excal.linagora.local
    environment:
      - OPENPAAS_URL=http://tcalendar-side-service.linagora.local
    volumes:
      - ./frontend/calendar/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - tcalendar

  fe-contacts:
    image: linagora/esn-frontend-contacts:17-01-2025
    hostname: contacts.linagora.local
    environment:
      - OPENPAAS_URL=http://tcalendar-side-service.linagora.local
    volumes:
      - ./frontend/contacts/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - tcalendar

  fe-account:
    image: linagora/esn-frontend-account:main
    hostname: account.linagora.local
    environment:
      - OPENPAAS_URL=http://tcalendar-side-service.linagora.local
    volumes:
      - ./frontend/account/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - tcalendar
    ports:
      - "8082:80"

  oidc:
    image: ghcr.io/dexidp/dex:latest
    container_name: sso.linagora.local
    ports:
      - "5556:5556"
    volumes:
      - ./oidc/dex_config.yaml:/etc/dex/config.yaml:ro
    command: dex serve /etc/dex/config.yaml
    networks:
      - tcalendar

  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: rabbitmq
    networks:
      - tcalendar
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: tcalendar
      RABBITMQ_DEFAULT_PASS: tcalendar

  sabre_dav:
    image: linagora/esn-sabre:sabre-4_7_0-09-12-2025
    container_name: sabre_dav
    hostname: sabre-dav.linagora.local
    networks:
      - tcalendar
    environment:
      - ESN_PORT=80
      - SABRE_ADMIN_LOGIN=admin
      - SABRE_ADMIN_PASSWORD=secret123
      - OPENPASS_BASIC_AUTH=YWRtaW5AbGluYWdvcmEubG9jYWw6c2VjcmV0
    volumes:
      - ./conf-side-service/jwt_publickey:/var/www/config/esn.key.pub
      - ./sabre/config.json:/var/www/config.json:ro
    depends_on:
      ferretdb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:80"

  web-proxy:
    image: nginx:alpine
    hostname: nginx.local
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - oidc
      - tcalendar-side-service
    networks:
      tcalendar:
        ipv4_address: 172.32.32.32

  redis:
    image: redis:6.2.6
    container_name: redis
    networks:
      - tcalendar
    ports:
      - "6379:6379"

  mock-smtp:
    image: linagora/mock-smtp-server:0.7
    container_name: smtp-server.local
    ports:
      - "8888:8000"
    networks:
      - tcalendar

  provision-data:
    image: postgres:17-alpine
    depends_on:
      postgres:
        condition: service_started
      tcalendar-side-service:
        condition: service_started
    volumes:
      - ./script:/script:ro
    entrypoint: ["sh", "/script/provision_entrypoint.sh"]
    environment:
      PGPASSWORD: password
    networks:
      - tcalendar
    restart: "no"

  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.107.0-ferretdb-2.7.0
    restart: on-failure
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - tcalendar

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.7.0
    restart: on-failure
    container_name: mongo
    depends_on:
      - postgres
    ports:
      - "27017:27017"
    environment:
      - FERRETDB_LOG_LEVEL=debug
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres?sslmode=disable
    networks:
      - tcalendar
